### ISSUE TITLE
setOverlap programmatically

### ISSUE THREAD

**Issue by MeinLieberScholli** [santalu/diagonal-imageview#4]
Like setPosition and setDirection, there should be a possibility to change the overlap.

**Comment by MeinLieberScholli** [comment]
Also, setPosition and setDirection like they are now, are not working because the Path is not updated.
It should look like this:
```    
    public void setOverlap(int overlap) {
        if (this.overlap != overlap) {
            this.overlap = overlap;
            setClipPath(getWidth(), getHeight());
            this.postInvalidate();
        }
    }
```

**Comment by MeinLieberScholli** [comment]
Thanks for the update. But what about the issue that all set Methods are not working, because the Path is not updated.
Am i missing something?

**Comment by santalu** [comment]
Hi, thanks for the feedback. I see all set methods working from examples.
Can you please give me some more details about what exactly are you trying?

**Comment by MeinLieberScholli** [comment]
Well, your example is working because you are not really using the set methods.
For example...
In the RecyclerViewSampleActivity in the bind method of the ViewHolder you are setting the position. And it works, but only because the ClipPath is generated afterwards.
If you add `image.setOverlap(35);` after line 80 in the RecyclerViewSampleActivity and click on any image... you will realize that the ClipPath is only reseted, but not updated.
That's why i proposed the code above.

Btw, getOverlap method is missing.

**Comment by santalu** [comment]
Hi. I made the calculation in `onLayout()` method that's why.  I did the necessary improvements. New usage is like this:
```
imageView.setPosition(DiagonalImageView.BOTTOM)
        .setDirection(DiagonalImageView.RIGHT)
        .setOverlap(300)
        .invalidate();
```
`invalidate()` method immediately generates clipPath with provided parameters.

I'll create a pre release asap. Please give me feedback after trying this. Thanks in advance.
